# Generated by Django 4.2 on 2023-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=350)),
            ],
        ),
    ]
