# Generated by Django 4.2 on 2023-06-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_district_places_name_url_branch_alter_places_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('dob', models.DateField(auto_now=True)),
                ('mobile', models.CharField(max_length=13)),
                ('mailid', models.CharField(max_length=250)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='bankapp.district'),
        ),
    ]
